export const PERSONALSTOCKTAB_SORT = 'PERSONALSTOCKTAB_SORT'
export const SET_PERSONAL_STOCK_DATA = 'SET_PERSONAL_STOCK_DATA'
export const ADD_PERSONAL_STOCK = 'ADD_PERSONAL_STOCK'
export const REMOVE_PERSONAL_STOCK = 'REMOVE_PERSONAL_STOCK'
export const ADD_HISTORY_STOCKS = 'ADD_HISTORY_STOCKS'
export const CLEAR_HISTORY_STOCKS = 'CLEAR_HISTORY_STOCKS'
export const MIN_CHART_DATA = 'MIN_CHART_DATA'
export const MIN_STOCK_INFO = 'MIN_STOCK_INFO'
export const MIN_JY_SHIJIANDUAN = 'MIN_JY_SHIJIANDUAN'
export const SET_K_CHART_STOCK_INFO = 'SET_K_CHART_STOCK_INFO'
export const SET_K_CHART_DATA = 'SET_K_CHART_DATA'
export const SET_MAIN_FORMULA = 'SET_MAIN_FORMULA'
export const SET_VICE_FORMULA = 'SET_VICE_FORMULA'
export const SET_SHOW_COUNT = 'SET_SHOW_COUNT'
export const SET_START_POSTION = 'SET_START_POSTION'
export const SET_LEGEND_POSITION = 'SET_LEGEND_POSITION'



export const SET_SEARCH_CONTENT = 'SET_SEARCH_CONTENT'
export const SHOW_KEYBOARD = 'SHOW_KEYBOARD'
export const SET_SEARCH_RESULT_LIST = 'SET_SEARCH_RESULT_LIST'
export const SET_LOADING_MESSAGE = 'SET_LOADING_MESSAGE'
export const SET_PERSONAL_NEWS_LIST_DATA = 'SET_PERSONAL_NEWS_LIST_DATA'
export const SET_NET_IS_CONNECT = 'SET_NET_IS_CONNECT'
export const SET_NET_CONNECT_INFO = 'SET_NET_CONNECT_INFO'

//用户登录
export const USER_LOGIN = 'USER_LOGIN';//登录
export const USER_LOGIN_INFO = 'USER_LOGIN_INFO';//登录成功后用户信息
export const USER_INFO_CHANGE = 'USER_INFO_CHANGE'; //修改用户信息
export const USER_LOGIN_TOKEN = 'USER_LOGIN_TOKEN'; //登录token
export const USER_LOGIN_POWER = 'USER_LOGIN_POWER'; //获取用户权限信息
export const USER_PUBLISH_SUBJECT = 'USER_PUBLISH_SUBJECT'; //用户发表主题
export const USER_COLLECT_SUBJECT = 'USER_COLLECT_SUBJECT'; //用户添加收藏
export const USER_REMOVE_COLLECT_SUBJECT = 'USER_REMOVE_COLLECT_SUBJECT'; //用户移除收藏

export const USER_SAVE_ALL_STOCKS = 'USER_SAVE_ALL_STOCKS';//保存所有本地数据顺序
export const USER_REMOVE_PERSON_STOCKS = 'USER_REMOVE_PERSON_STOCKS';//移除游客本地数据

export const USER_CENTER_ALL_DATA = 'USER_CENTER_ALL_DATA';//我的数据
export const USER_ALL_DATA_APP2 = 'USER_ALL_DATA_APP2';//APP2 users 数据
export const USER_LOGOUT = 'USER_LOGOUT'; //退出
export const USER_PASSWORD = 'USER_PASSWORD'; //用户密码

export const USER_CENTER_CUSTOMER = 'USER_CENTER_CUSTOMER';//测试 客服聊天 客服
export const USER_CENTER_IM_MESSAGE = 'USER_CENTER_IM_MESSAGE'; //聊天消息
export const USER_CENTER_IM_KFINFO = 'USER_CENTER_IM_KFINFO'; //聊天 客服信息
export const USER_CENTER_IM_LOGOUT = 'USER_CENTER_IM_LOGOUT'; //退出聊天界面

export const TEACHER_CENTER_CUSTOMER = 'TEACHER_CENTER_CUSTOMER';//阿丁聊天
export const TEACHER_CENTER_IM_MESSAGE = 'TEACHER_CENTER_IM_MESSAGE'; //阿丁聊天
export const TEACHER_CENTER_IM_INFO = 'TEACHER_CENTER_IM_INFO'; // 阿丁聊天
export const TEACHER_CENTER_IM_LOGOUT = 'TEACHER_CENTER_IM_LOGOUT'; //阿丁聊天

export const USER_CENTER_MESSAGE_GONGGAO = 'USER_CENTER_MESSAGE_GONGGAO';//消息中的公告
export const USER_CENTER_MESSAGE_GONGGAO_ALERT = 'USER_CENTER_MESSAGE_GONGGAO_ALERT';//消息中的公告提示
export const USER_CENTER_ZAN_MESSAGE = 'USER_CENTER_ZAN_MESSAGE' //用户所有点赞的数据

export const USER_IS_FIRST_USE = 'USER_IS_FIRST_USE';//是否是第一次使用
export const USER_APP_SS0 = 'USER_APP_SS0';//用户单点登录
export const USER_ONLINE_COLLECTION_TIME = 'USER_ONLINE_COLLECTION_TIME';//在线征集时间

export const USER_LOGIN_ADD_HISTORYS = 'USER_LOGIN_ADD_HISTORYS';//添加历史用户记录

export const USER_PERSON_STOCK_TOP = 'USER_PERSON_STOCK_TOP';//自选股置顶

export const GET_APP_VERSION = 'GET_APP_VERSION'; //获取版本信息
export const GET_APP_IOSCHECK = 'GET_APP_IOSCHECK'; //获取ios 版本状态


export const USER_YXHD_INFO = 'USER_YXHD_INFO';//营销活动


